In [2]:
import numpy as np

In [3]:
np.__version__

'2.1.3'

### creating list

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

#### 1D Array

In [6]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
type(my_list)

list

#### np.arange

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [12]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
np.arange(20,10)

array([], dtype=int64)

In [15]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [16]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [17]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [18]:
np.arange()

TypeError: arange() requires stop to be specified.

In [19]:
np.arange(10,30,5) #start, stop and step

array([10, 15, 20, 25])

In [20]:
np.arange(10,20,3)

array([10, 13, 16, 19])

In [21]:
np.arange(10,30,8,5) #np.arange function we pass maximum three numbers 

TypeError: Cannot interpret '5' as a data type

#### np.zeros

In [22]:
np.zeros(3) #parameter tunning

array([0., 0., 0.])

In [23]:
np.zeros(3,dtype=int) #hyperparameter tunning

array([0, 0, 0])

#### 2D Array

In [24]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
np.zeros((2,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [26]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### np.ones

In [27]:
np.ones(3)

array([1., 1., 1.])

In [28]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [29]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [30]:
np.two((5)) #only zero and one is allowed 

AttributeError: module 'numpy' has no attribute 'two'

#### np.random

In [31]:
import random

In [32]:
rand(3,2)

NameError: name 'rand' is not defined

In [33]:
random.rand(3,2)

AttributeError: module 'random' has no attribute 'rand'

In [34]:
random.random()

0.21010153620157856

In [35]:
np.random.rand(5)

array([0.76478269, 0.5606609 , 0.33514301, 0.56113307, 0.00098656])

In [36]:
np.random.rand(3,5)

array([[0.46992091, 0.61891564, 0.41858374, 0.79058398, 0.33539518],
       [0.24988366, 0.827488  , 0.2980237 , 0.27573098, 0.71326886],
       [0.28927284, 0.20811625, 0.72840636, 0.57441182, 0.5754534 ]])

#### np.random.randint

In [37]:
np.random.randint(4,6)

5

In [57]:
np.random.randint(2,20,4)

array([16,  2,  4, 11], dtype=int32)

In [58]:
np.random.randint(30,20,10) #1 argument should always smaller than 2

ValueError: low >= high

In [60]:
np.random.randint(-30,20,10)

array([-23, -25, -30,  -7, -28,   7, -20, -11,  16,  14], dtype=int32)

In [65]:
np.random.randint(10,40,(10,10)) #10x10 matrix

array([[15, 30, 37, 12, 22, 16, 17, 25, 15, 33],
       [19, 20, 32, 25, 14, 31, 11, 33, 26, 14],
       [35, 28, 34, 34, 23, 29, 14, 12, 39, 28],
       [16, 32, 24, 35, 12, 25, 20, 28, 18, 13],
       [28, 27, 22, 21, 32, 24, 28, 29, 15, 34],
       [17, 22, 16, 17, 31, 13, 15, 35, 36, 30],
       [39, 35, 27, 36, 37, 16, 37, 21, 33, 10],
       [23, 14, 10, 16, 11, 23, 25, 17, 31, 33],
       [19, 26, 32, 22, 26, 30, 28, 16, 26, 30],
       [30, 24, 26, 38, 25, 19, 38, 32, 15, 29]], dtype=int32)

In [37]:
np.random.randint(10,40,(8,8)) #8x8 matrix

array([[18, 10, 37, 16, 37, 10, 36, 36],
       [25, 19, 35, 17, 17, 18, 24, 10],
       [16, 36, 31, 35, 35, 37, 37, 32],
       [36, 32, 14, 16, 14, 16, 38, 38],
       [16, 36, 35, 34, 17, 29, 24, 33],
       [16, 28, 28, 27, 25, 22, 37, 37],
       [26, 25, 34, 36, 26, 17, 22, 35],
       [39, 27, 37, 26, 30, 10, 33, 20]], dtype=int32)

In [68]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### .reshape

In [69]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
np.arange(1,16).reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [39]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [73]:
b = np.random.randint(10,20,(5,4))
b

array([[14, 14, 13, 16],
       [16, 16, 10, 13],
       [16, 14, 17, 19],
       [16, 18, 14, 14],
       [19, 13, 16, 12]], dtype=int32)

# slicing in matrix

In [1]:
import numpy as np

In [4]:
b = np.random.randint(10,20,(5,6))

In [5]:
b

array([[12, 19, 17, 14, 18, 11],
       [13, 11, 17, 16, 15, 14],
       [14, 11, 14, 15, 11, 11],
       [13, 12, 19, 16, 17, 14],
       [10, 15, 14, 10, 16, 17]], dtype=int32)

In [6]:
type(b)

numpy.ndarray

In [7]:
b[0]

array([12, 19, 17, 14, 18, 11], dtype=int32)

In [8]:
b[:]

array([[12, 19, 17, 14, 18, 11],
       [13, 11, 17, 16, 15, 14],
       [14, 11, 14, 15, 11, 11],
       [13, 12, 19, 16, 17, 14],
       [10, 15, 14, 10, 16, 17]], dtype=int32)

In [9]:
b[:3]

array([[12, 19, 17, 14, 18, 11],
       [13, 11, 17, 16, 15, 14],
       [14, 11, 14, 15, 11, 11]], dtype=int32)

In [11]:
b[-1]

array([10, 15, 14, 10, 16, 17], dtype=int32)

In [12]:
b[0][4]

np.int32(18)

In [13]:
b[1:4]

array([[13, 11, 17, 16, 15, 14],
       [14, 11, 14, 15, 11, 11],
       [13, 12, 19, 16, 17, 14]], dtype=int32)

In [14]:
b[1,4]

np.int32(15)

In [15]:
b[0,2]

np.int32(17)

In [18]:
b

array([[12, 19, 17, 14, 18, 11],
       [13, 11, 17, 16, 15, 14],
       [14, 11, 14, 15, 11, 11],
       [13, 12, 19, 16, 17, 14],
       [10, 15, 14, 10, 16, 17]], dtype=int32)

In [20]:
b[2:-1]

array([[14, 11, 14, 15, 11, 11],
       [13, 12, 19, 16, 17, 14]], dtype=int32)

In [21]:
b[0:-2]

array([[12, 19, 17, 14, 18, 11],
       [13, 11, 17, 16, 15, 14],
       [14, 11, 14, 15, 11, 11]], dtype=int32)

In [22]:
b[0,-2]

np.int32(18)

In [23]:
b[-4,-3]

np.int32(16)

## operation

In [25]:
c = np.random.randint(10,20,10)
c

array([19, 11, 14, 17, 10, 18, 14, 13, 10, 15], dtype=int32)

In [27]:
id(c)

1964754845936

In [30]:
arr = np.random.randint(0,100,(10,10))
arr

array([[72, 89, 14, 82,  5, 30, 15, 98, 18, 61],
       [13,  8, 53, 58, 43, 67, 63, 26, 50, 50],
       [ 9, 38, 21, 16, 90, 99, 73, 66, 10, 94],
       [27, 20, 10, 98, 58,  6, 59, 64, 28, 53],
       [46, 87, 25, 76, 10,  2, 87, 95, 54, 64],
       [62, 83,  3, 49, 42, 26, 98, 81, 65, 60],
       [55, 59, 79, 30, 83, 82, 85, 31, 64, 99],
       [14, 77, 23,  4, 22, 64, 33, 21, 50, 73],
       [31, 92, 89, 34, 62, 74, 61, 63, 83, 99],
       [24, 59, 39, 39, 82, 38, 42, 64, 46,  5]], dtype=int32)

In [32]:
arr[::-1]

array([[24, 59, 39, 39, 82, 38, 42, 64, 46,  5],
       [31, 92, 89, 34, 62, 74, 61, 63, 83, 99],
       [14, 77, 23,  4, 22, 64, 33, 21, 50, 73],
       [55, 59, 79, 30, 83, 82, 85, 31, 64, 99],
       [62, 83,  3, 49, 42, 26, 98, 81, 65, 60],
       [46, 87, 25, 76, 10,  2, 87, 95, 54, 64],
       [27, 20, 10, 98, 58,  6, 59, 64, 28, 53],
       [ 9, 38, 21, 16, 90, 99, 73, 66, 10, 94],
       [13,  8, 53, 58, 43, 67, 63, 26, 50, 50],
       [72, 89, 14, 82,  5, 30, 15, 98, 18, 61]], dtype=int32)

In [33]:
arr[::-2]

array([[24, 59, 39, 39, 82, 38, 42, 64, 46,  5],
       [14, 77, 23,  4, 22, 64, 33, 21, 50, 73],
       [62, 83,  3, 49, 42, 26, 98, 81, 65, 60],
       [27, 20, 10, 98, 58,  6, 59, 64, 28, 53],
       [13,  8, 53, 58, 43, 67, 63, 26, 50, 50]], dtype=int32)

In [34]:
arr[::-3]

array([[24, 59, 39, 39, 82, 38, 42, 64, 46,  5],
       [55, 59, 79, 30, 83, 82, 85, 31, 64, 99],
       [27, 20, 10, 98, 58,  6, 59, 64, 28, 53],
       [72, 89, 14, 82,  5, 30, 15, 98, 18, 61]], dtype=int32)

In [35]:
arr

array([[72, 89, 14, 82,  5, 30, 15, 98, 18, 61],
       [13,  8, 53, 58, 43, 67, 63, 26, 50, 50],
       [ 9, 38, 21, 16, 90, 99, 73, 66, 10, 94],
       [27, 20, 10, 98, 58,  6, 59, 64, 28, 53],
       [46, 87, 25, 76, 10,  2, 87, 95, 54, 64],
       [62, 83,  3, 49, 42, 26, 98, 81, 65, 60],
       [55, 59, 79, 30, 83, 82, 85, 31, 64, 99],
       [14, 77, 23,  4, 22, 64, 33, 21, 50, 73],
       [31, 92, 89, 34, 62, 74, 61, 63, 83, 99],
       [24, 59, 39, 39, 82, 38, 42, 64, 46,  5]], dtype=int32)

In [36]:
arr[:-3]

array([[72, 89, 14, 82,  5, 30, 15, 98, 18, 61],
       [13,  8, 53, 58, 43, 67, 63, 26, 50, 50],
       [ 9, 38, 21, 16, 90, 99, 73, 66, 10, 94],
       [27, 20, 10, 98, 58,  6, 59, 64, 28, 53],
       [46, 87, 25, 76, 10,  2, 87, 95, 54, 64],
       [62, 83,  3, 49, 42, 26, 98, 81, 65, 60],
       [55, 59, 79, 30, 83, 82, 85, 31, 64, 99]], dtype=int32)

In [37]:
arr[0:10:3]

array([[72, 89, 14, 82,  5, 30, 15, 98, 18, 61],
       [27, 20, 10, 98, 58,  6, 59, 64, 28, 53],
       [55, 59, 79, 30, 83, 82, 85, 31, 64, 99],
       [24, 59, 39, 39, 82, 38, 42, 64, 46,  5]], dtype=int32)

In [38]:
arr[0:8:2]

array([[72, 89, 14, 82,  5, 30, 15, 98, 18, 61],
       [ 9, 38, 21, 16, 90, 99, 73, 66, 10, 94],
       [46, 87, 25, 76, 10,  2, 87, 95, 54, 64],
       [55, 59, 79, 30, 83, 82, 85, 31, 64, 99]], dtype=int32)

In [39]:
arr

array([[72, 89, 14, 82,  5, 30, 15, 98, 18, 61],
       [13,  8, 53, 58, 43, 67, 63, 26, 50, 50],
       [ 9, 38, 21, 16, 90, 99, 73, 66, 10, 94],
       [27, 20, 10, 98, 58,  6, 59, 64, 28, 53],
       [46, 87, 25, 76, 10,  2, 87, 95, 54, 64],
       [62, 83,  3, 49, 42, 26, 98, 81, 65, 60],
       [55, 59, 79, 30, 83, 82, 85, 31, 64, 99],
       [14, 77, 23,  4, 22, 64, 33, 21, 50, 73],
       [31, 92, 89, 34, 62, 74, 61, 63, 83, 99],
       [24, 59, 39, 39, 82, 38, 42, 64, 46,  5]], dtype=int32)

In [42]:
arr2 =np.array([0,1,2,3,4,5])

In [43]:
arr2

array([0, 1, 2, 3, 4, 5])

In [46]:
arr2.max()

np.int64(5)

In [47]:
arr2.max()

np.int64(5)

In [48]:
arr2.mean()

np.float64(2.5)

In [49]:
arr2.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [52]:
from numpy import *
a = array([0,1,2,3,4,5])
median(a)

np.float64(2.5)

## indedxing

In [53]:
mat = arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [54]:
row = 5
col = 4

In [55]:
col

4

In [56]:
row

5

In [57]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [59]:
mat[row,col]

np.int64(54)

In [60]:
mat[4,2]

np.int64(42)

In [61]:
mat[0,8]

np.int64(8)

In [62]:
#with slices
mat[:,col] #print column

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [64]:
mat[:,6]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [65]:
mat[2:8]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [68]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [70]:
mat[5:-1]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [71]:
mat[:-5]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [72]:
mat[6,8]

np.int64(68)

In [73]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [74]:
mat[2:6,2:4] #2:6 consider as row 2:4 consider as column

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [75]:
mat[1:2,4:8]

array([[14, 15, 16, 17]])

In [76]:
mat[2:3,2:3]

array([[22]])

In [77]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [78]:
mat[2:3,4:5]

array([[24]])

# numpy masking

In [80]:
mat #we are also called as filters

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [81]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [82]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [83]:
mat[mat>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [85]:
mat[mat==50]

array([50])

In [86]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [87]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [88]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])